[package]
name = "parity-hash"
version = "1.0.0"
description = "A collection of fixed-size byte array representations"
authors = ["Alexey Frolov <alexey@parity.io>"]
license = "MIT"

[dependencies]
bigint = "4"
rustc-hex = "1.0"

[features]
default = ["std"]
std = ["bigint/std"]
